### PR TITLE
Added a new volley enchant for bows

### PR DESCRIPTION
**Pull request by fantasm0**
Hi, I added an extra enchantment for bows (Volley), which fires multiple arrows in a cone in front of you (lvl1 --> 3 arrows, lvl2 --> 5 arrows). Other custom enchantments for bows can be combined with this to create powerful effects. Currently standard minecraft enchantments don't work, but that's not too hard to add. Some of the code might be a little messy becaus of the annoying pitch and yaw to Vector conversion. 

Apart from the volley i changed the visibility of handleEventMain to public (All others are public, guess this one should be too?). I had to change some extra small things (casts to (HashSet<Material>)), those were errors i had on my initial fork. 

Let me know what you think about this.

kind regards, fantasm0

### CODE REVIEW

**Comment by fantasm0** [comment]
I haven't made sure that the enchantMentMaxLevel is set properly yet. I'll Have to either set that to 2 or make the amount of arrows based on the enchantment level, which might be a far better solution. But I'll wait for your reply first.

**Comment by Taiterio** [comment]
Heyo,

Just refitted your contribution a bit, it is really cool to see :)

First of all, casting the null values to the HashSets should not be done since they are not supposed to have any kind of value, if a warning comes up, add @SurpressWarnings to the function in question :)

Furthermore, the handleEventMain is private as no other class should get direct access to it, since it has to pass the other listener events beforehand; I may change the wording a bit later on to better differentiate it from the other handlers.

For your contribution, I have removed some unused values (sX and sY), cleaned the code up a little bit and removed the part where you set the metadata of the arrow, since that is done by the EventHandler. The maximum level is set to 5 as is standard for every non-onelevel enchantment in CE, it has a really cool effect to see it go up to level 10 though :D

For the vanilla enchantments being made compatible I'd have to say that this will have to wait from my side, if you want to take this part over, feel free to do so. I have tried to duplicate arrows or the event that created it, but it seems like you would have to implement all effects of the vanilla enchantments yourself and save it into the metadata of the arrow. 

As a last note, the variable configEntries defines the entries in the config that this enchantment has in addition to the standard entries like displayname, enchantment probability, etc. - to add an entry you would have to add the config entry to the list configEntries in the following way: 

configEntries.add("ConfigEntryName: Value");

Afterwards, you would go into initConfigEntries() of your enchantment and initialize the value. This has to be done to allow the configuration to automatically write and read itself. When initializing the values you have to keep in mind though that ALL entries in the config are to be considered strings, so you would have to parse any other datatype accordingly.

If you have anymore questions as to how the system works in further detail, feel free to leave them here :)

Thanks for your contribution, 

- Taiterio

**Comment by Taiterio** [comment]
Found a small bug, players could duplicate arrows since they shot 1 arrow, but were able to pick up any of the new ones, fixed that really quick aswell :)

- Taiterio

**Comment by fantasm0** [comment]
While making the enchantment i thought of arrow duplication, apparently i forgot about it (should have put that on my to-do list). 

I took a quick look at supporting standard enchantments as well, but like you said it doesn't seem as simple as just duplicating the arrows unfortunately. If you want i'll look into this a bit more when i have some spare time (I have some very busy weeks coming up, so this might take a while).

I'm definitely planning on contributing some more, it might take a while though.

**Comment by Taiterio** [comment]
Alright :)

**Comment by fantasm0** [comment]
BTW, i added that metadata because the eventhandler only adds it to the original arrow. I remove the original arrow and spawn a cone of new arrows. Those new arrows need the metadata from that original arrow to be compatible with other custom enchantments.

**Comment by Taiterio** [comment]
I noticed I made some mistakes in the refitting :D

So, the casts of the null values seems to have been blocked by me having changed that in my IDE, I see why it is needed now though, so sorry for that :)

The metadata went into the right direction, but it had to be done in another way, which I have implemented in commit 8f4ed84b103ba5ca50a404efb683dad7e238d832

So sorry for that aswell, I'll check these things more closely next time :)

**Comment by fantasm0** [comment]
Allright, I see you added the standard minecraft enchantments but this only works for fire and knockback atm right? When I was looking into it I didn't see support for the punch enchantment (extra dmg) in the arrow class, so I don't really know how that is handled. This can be done on the EntityDamageByEntity event (checking if bow in hand has punch, and setting the damage of the event accordingly) but then it would be seperated from the other enchantment code, so that would not be very clean.

**Comment by Taiterio** [comment]
The extra damage bow enchantment could be implemented rather easily checking if the arrow has the enchantment and then setting some metadata on the arrows that could later on be read in the damage event. I don't think that it would be that much of a problem to see this rather short passage of code put into the EntityDamageByEntity event :)

**Pull request closed without merging**
